<!-- Faja CTA -->
<section class="container-fluid faja_destacado_sec">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center align_vertical_horizontal">
				<div>
					<h4 class="h4_electronica">¿Necesitas asesoramiento?</h4>
					<a href="contacto.php" class="btn_cta_electronica btn_sm margin_top_10">CONTACTAR</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Faja CTA end-->