<footer class="container-fluid">
  <div class="row">
    <div
      class="col-md-6 text-center align_vertical_horizontal margin_bottom_30">
      <div>
        <img
          class="logo_footer"
          src="img/logo_footer.png"
          alt="logo imprac footer" />
      </div>
    </div>

    <div class="col-md-6 align_vertical_horizontal">
      <div>
        <span>
          <a href="tel:1144884418"
            ><i class="fas fa-phone"></i>+54.011.4488.4418</a
          >
        </span>
        <br />
        <span>
          <a href="mailto:info@imprac.com.ar"
            ><i class="fas fa-envelope"></i>info@imprac.com.ar</a
          >
        </span>
        <span>
          <br />
          <a
            href="https://maps.app.goo.gl/dpkErSLFZYFFyZuu7"
            target="_blank"
            rel="noopener"
            ><i class="fas fa-map-marker"></i>Barragan 855, Ciudadela Norte.
            <br />
            Buenos Aires - Argentina</a
          >
        </span>
        <br />
        <span>
          <a href="http://imprac.com.ar/" target="_blank"
            ><i class="fas fa-globe"></i>www.imprac.com.ar</a
          >
        </span>
        <br />
      </div>
    </div>
  </div>

  <div class="row margin_top_10">
    <div class="col-md-12 text-center">
      <p class="derechos_reservados_footer">
        &reg;
        <?= date('Y'); ?>
        - IMPRAC todos los derechos reservados.
      </p>
    </div>
  </div>

  <div class="row margin_top_10">
    <div class="col-md-12 text-center">
      <a class="libre_footer" href="#">by Libre</a>
    </div>
  </div>
</footer>
