<!-- Faja taller y sello -->
<section class="container-fluid taller_sello align_vertical_horizontal">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <div>
          <h4 class="frase_argentina_home">
            Pensamos en grande para ofrecerte productos sólidos, precisos y listos para desafiar el día a día.
          </h4>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Faja taller y sello end-->
