<!-- Faja taller y sello -->
<section class="container-fluid taller_sello align_vertical_horizontal">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div>
					<img class="sello_argentina" src="img/sello.png" alt="sello argentina">
					<h4 class="frase_argentina_home">
						"Somos una empresa orgullosamente Argentina, que piensa, proyecta y produce en el país productos de primera calidad."
					</h4>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Faja taller y sello end-->