<!-- Slider con fondo-->
<section class="fondo-slide container-fluid">
  <!-- Slider Large -->
  <section class="slider-wrapper padding_top_60">
    <div class="responisve-container">
      <div class="slider">
        <div class="fs_loader"></div>

        <!-- Slider Corredizos -->
        <div class="slide">
          <h2
            class="parrafo_slide h2_slide_home"
            data-position="80,50"
            data-in="top"
            data-out="top"
            data-delay="300"
          >
            AUTOMATIZACIÓN
          </h2>
          <p
            class="parrafo_slide p_slide_home"
            data-position="170,40"
            data-in="right"
            data-out="left"
            data-delay="600"
          >
            Conocé nuestra completa línea de motores <br />
            para portones corredizos.
          </p>
          <a
            href="corredizos.php"
            class="btn_slide_home"
            data-position="270,200"
            data-in="bottom"
            data-out="bottom"
            data-delay="900"
          >
            VER MÁS
          </a>
          <img
            src="img/slide-home/slide-home-corredizos-mod-gr.png"
            data-position="-70,580"
            data-in="left"
            data-out="top"
          />
        </div>
        <!-- Slider Corredizos end -->

        <!-- Slider Levadizos -->
        <div class="slide">
          <h2
            class="parrafo_slide h2_slide_home"
            data-position="80,50"
            data-in="top"
            data-out="top"
            data-delay="300"
          >
            AUTOMATIZACIÓN
          </h2>
          <p
            class="parrafo_slide p_slide_home"
            data-position="170,40"
            data-in="right"
            data-out="left"
            data-delay="600"
          >
            Conocé nuestra completa línea de motores <br />
            para portones levadizos.
          </p>
          <a
            href="levadizos.php"
            class="btn_slide_home"
            data-position="270,200"
            data-in="bottom"
            data-out="bottom"
            data-delay="900"
          >
            VER MÁS
          </a>
          <img
            src="img/slide-home/slide-home-levadizo-gr.webp"
            data-position="-70,580"
            data-in="left"
            data-out="top"
          />
        </div>
        <!-- Slider Levadizos end -->

        <!-- Slider Electrónica -->
        <div class="slide">
          <h2
            class="parrafo_slide h2_slide_home"
            data-position="80,50"
            data-in="top"
            data-out="top"
            data-delay="300"
          >
            ELECTRÓNICA
          </h2>
          <p
            class="parrafo_slide p_slide_home"
            data-position="170,0"
            data-in="right"
            data-out="left"
            data-delay="600"
          >
            Completa línea de dispositivos electrónicos <br />
            Centrales, Receptores, Transmisores, etc.
          </p>
          <a
            href="electronica.php"
            class="btn_slide_home"
            data-position="270,160"
            data-in="bottom"
            data-out="bottom"
            data-delay="900"
          >
            VER MÁS
          </a>
          <img
            src="img/slide-home/slide-home-electronica-gr.png"
            data-position="-70,580"
            data-in="left"
            data-out="top"
          />
        </div>
        <!-- Slider Electrónica end -->

        <!-- Slider Accesorios -->
        <div class="slide">
          <h2
            class="parrafo_slide h2_slide_home"
            data-position="80,110"
            data-in="top"
            data-out="top"
            data-delay="300"
          >
            ACCESORIOS
          </h2>
          <p
            class="parrafo_slide p_slide_home"
            data-position="170,5"
            data-in="right"
            data-out="left"
            data-delay="600"
          >
            Línea de accesorios utilizados como complemento <br />
            en la automatización de portones.
          </p>
          <a
            href="accesorios.php"
            class="btn_slide_home"
            data-position="270,200"
            data-in="bottom"
            data-out="bottom"
            data-delay="900"
          >
            VER MÁS
          </a>
          <img
            src="img/slide-home/slide-home-semaforo-gr.png"
            data-position="-70,580"
            data-in="left"
            data-out="top"
          />
        </div>
        <!-- Slider Accesorios end -->

        <!-- Slider Repuestos -->
        <div class="slide">
          <h2
            class="parrafo_slide h2_slide_home"
            data-position="80,110"
            data-in="top"
            data-out="top"
            data-delay="300"
          >
            REPUESTOS
          </h2>
          <p
            class="parrafo_slide p_slide_home"
            data-position="170,5"
            data-in="right"
            data-out="left"
            data-delay="600"
          >
            Disponemos de todos los repuestos necesarios para <br />
            las reparaciones de los sistemas de automatización
          </p>
          <a
            href="repuestos.php"
            class="btn_slide_home"
            data-position="270,200"
            data-in="bottom"
            data-out="bottom"
            data-delay="900"
          >
            VER MÁS
          </a>
          <img
            src="img/slide-home/slide-home-repuestos.png"
            data-position="-70,580"
            data-in="left"
            data-out="top"
            alt="repuestos imprac"
          />
        </div>
        <!-- Slider Repuestos end -->
      </div>
    </div>
  </section>
  <!-- Slider Large end -->

  <!-- Slider Medium y Small Home -->
  <section
    id="carouselExampleIndicators"
    class="slider_medium_small carousel slide text-center padding_top_60"
    data-ride="carousel"
  >
    <ol class="carousel-indicators">
      <li
        data-target="#carouselExampleIndicators"
        data-slide-to="0"
        class="active"
      ></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>

    <div class="carousel-inner">
      <!-- Slider Corredizos medium -->
      <div class="carousel-item active margin_bottom_30">
        <img
          class="d-block imgSlideHome"
          src="img/slide-home/slide-home-corredizos-mod.png"
          alt="Portones corredizos slide"
        />
        <div class="carousel-caption d-md-block">
          <h5>Motores Corredizos</h5>
          <p>Conocé toda la línea</p>
        </div>
      </div>
      <!-- Slider Corredizos medium  end-->

      <!-- Slider Levadizos medium -->
      <div class="carousel-item margin_bottom_30">
        <img
          class="d-block imgSlideHome"
          src="img/slide-home/slide-home-levadizo.webp"
          alt="Portones levadizos slide"
        />
        <div class="carousel-caption d-md-block">
          <h5>Motores Levadizos</h5>
          <p>Conocé toda la línea</p>
        </div>
      </div>
      <!-- Slider Levadizos medium  end-->

      <!-- Slider Electronica medium -->
      <div class="carousel-item margin_bottom_30">
        <img
          class="d-block imgSlideHome"
          src="img/slide-home/slide-home-electronica.png"
          alt="electronica slide"
        />
        <div class="carousel-caption d-md-block">
          <h5>Electrónica</h5>
          <p>Conocé toda la línea</p>
        </div>
      </div>
      <!-- Slider Electronica medium  end-->

      <!-- Slider Repuestos medium -->
      <div class="carousel-item margin_bottom_30">
        <img
          class="d-block imgSlideHome"
          src="img/slide-home/slide-home-semaforo.png"
          alt="repuestos slide"
        />
        <div class="carousel-caption d-md-block">
          <h5>Repuestos</h5>
          <p>Conocé toda la línea</p>
        </div>
      </div>
      <!-- Slider Repuestos medium  end-->
    </div>

    <a
      class="carousel-control-prev"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a
      class="carousel-control-next"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </section>
  <!-- Slider Medium y Small Home end-->

  <!-- CTA familia de productos home -->
  <section class="familia_home container">
    <div class="row text-center">
      <div class="col-lg-4">
        <a href="automatizacion-portones.php"
          ><img
            class="icono_familia_home margin_bottom_15"
            src="img/icono_automatizacion.png"
            alt="icono automatizacion"
        /></a>
        <h3>
          <a class="h3_familia_home" href="automatizacion-portones.php"
            >AUTOMATIZACIÓN</a
          >
        </h3>
        <p class="parrafo_familia_home">
          Completa línea de dispositivos electrónicos utilizados en la
          automatización de portones.
        </p>
      </div>

      <div class="col-lg-4">
        <a href="electronica.php"
          ><img
            class="icono_familia_home margin_bottom_15"
            src="img/icono_electronica.png"
            alt="icono electronica"
        /></a>
        <h3>
          <a class="h3_familia_home" href="electronica.php">ELECTRÓNICA</a>
        </h3>
        <p class="parrafo_familia_home">
          Línea de dispositivos electrónicos utilizados en la automatización de
          portones.
        </p>
      </div>

      <div class="col-lg-4">
        <a href="accesorios.php"
          ><img
            class="icono_familia_home margin_bottom_15"
            src="img/icono_accesorios.png"
            alt="icono accesorios"
        /></a>
        <h3><a class="h3_familia_home" href="accesorios.php">ACCESORIOS</a></h3>
        <p class="parrafo_familia_home">
          Amplia gama de componentes necesarios para el funcionamiento de los
          distintos sistemas.
        </p>
      </div>
    </div>
  </section>
  <!-- CTA familia de productos home end -->
</section>
<!-- Slider con fondo end -->
