<!-- Seccion Seguidor -->
<section id="seguidor" class="text-center animated fadeInRight">
  <button id="cerrar-seguidor" style="color: #000000;">
  	<i style="font-size: 1.25em; float: right;" class="fa fa-times-circle"></i>
  </button>
  
  <hr style="margin: 10px 0;">

  <div class="click-to-call-mobile">
    <i class="fab fa-whatsapp whatsapp"></i>
  </div>

  <h6><strong>¡CONSULTÁ POR WHATSAPP!</strong></h6>

  <a id="whatsapp_desktop" href="https://api.whatsapp.com/send?phone=5491130904101&text=Hola!%20Necesito%20hacer%20una%20consulta!" target="_blank" class="btn btn-wap">
		CHAT
	</a>
</section>

<section id="seguidor-tel" class="text-center">
	<div class="tex-right">
    <button id="cerrar-seguidor-tel" style="color: #000000;">
      <i style="font-size: 1.25em;" class="fa fa-times-circle"></i>
    </button>
	</div>
  <a id="whatsapp_mobile" class="transition" href="https://api.whatsapp.com/send?phone=5491130904101&text=Hola!%20Necesito%20hacer%20una%20consulta!" target="_blank">
		<h5>¡CONSULTÁ POR <br> WHATSAPP!</h5>
	</a>
</section>
<!-- Fin Seccion Seguidor -->